# -*- coding: utf-8 -*-
"""webm_to_mp4_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmfMowzqiFkcJxjl9uwIJOMyTPx_ZfZ5
"""

!git clone https://github.com/achilela/convert_webm_mp4.git

!pip install -r /content/convert_webm_mp4/requirements.txt

!streamlit run /content/convert_webm_mp4/streamlit-webm-to-mp4-converter.py

# Commented out IPython magic to ensure Python compatibility.
# %cd convert_webm_mp4

# Add the files to the staging area
!git add .

# Commit the changes
!git commit -m "Initial commit"

# Push the changes to the remote repository
!git push -u origin master

!git config --global user.email "ataliba.miguel@myport.ac.uk"
!git config --global user.name "achilela"